import type { Metadata } from "next";
import { Footer, Layout, Navbar } from "nextra-theme-docs";
import { Banner, Head } from "nextra/components";
import { getPageMap } from "nextra/page-map";
import "nextra-theme-docs/style.css";
import { SkalaLogo } from "@/components/ui/logo";
import "./globals.css";

export const metadata: Metadata = {
  metadataBase: new URL("https://nextra.site"),
  title: "%s - Nextra",
  description: "Nextra: the Next.js site builder",
  applicationName: "Nextra",
  generator: "Next.js",
  appleWebApp: {
    title: "Nextra",
  },
  other: {
    "msapplication-TileImage": "/ms-icon-144x144.png",
    "msapplication-TileColor": "#fff",
  },
  twitter: {
    site: "https://nextra.site",
  },
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navbar = (
    <Navbar logo={<SkalaLogo width={150} />} chatLink="https://skala.xyz" />
  );
  return (
    <html lang="en" dir="ltr" suppressHydrationWarning>
      <Head faviconGlyph="✦" />
      <body>
        <Layout
          banner={<Banner storageKey="Nextra 2">Nextra 2 Alpha</Banner>}
          navbar={navbar}
          footer={<Footer />}
          editLink="Edit this page on GitHub"
          docsRepositoryBase="https://github.com/shuding/nextra/blob/main/examples/docs"
          sidebar={{ defaultMenuCollapseLevel: 1 }}
          pageMap={await getPageMap()}
        >
          {children}
        </Layout>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import { Footer, Layout, Navbar } from "nextra-theme-docs";
// import { Banner, Head } from "nextra/components";
// import { Geist, Geist_Mono } from "next/font/google";
// import { getPageMap } from "nextra/page-map";
// import "nextra-theme-docs/style.css";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default async function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   const navbar = (
//     <Navbar
//       logo={
//         <div>
//           <b>Nextra</b>{" "}
//           <span style={{ opacity: "60%" }}>The Next Docs Builder</span>
//         </div>
//       }
//       // Next.js discord server
//       chatLink="https://discord.gg/hEM84NMkRv"
//     />
//   );

//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Layout
//           banner={<Banner storageKey="Nextra 2">Nextra 2 Alpha</Banner>}
//           navbar={navbar}
//           footer={<Footer />}
//           editLink="Edit this page on GitHub"
//           docsRepositoryBase="https://github.com/shuding/nextra/blob/main/examples/docs"
//           sidebar={{ defaultMenuCollapseLevel: 1 }}
//           pageMap={await getPageMap()}
//         >
//           {children}
//         </Layout>
//       </body>
//     </html>
//   );
// }
